---
- hosts: web
  become: yes
  vars_files:
    - vars/docker.yml

  tasks:
    - name: Install aptitude using apt
      remote_user: ubuntu
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages for Docker
      remote_user: ubuntu
      apt: name={{ docker_required_packages }} state=latest update_cache=yes

    - name: Add Docker GPG key
      remote_user: ubuntu
      apt_key:
        url: "{{ docker_gpg_url }}"
        state: present

    - name: Add Docker repository
      remote_user: ubuntu
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: Install Docker
      remote_user: ubuntu
      apt: name={{ docker_packges }} state=latest update_cache=yes

    - name: Install Python Docker module
      remote_user: ubuntu
      pip:
        name: docker

    - name: Add adminstrator to docker group
      remote_user: ubuntu
      user:
        name: "ubuntu"
        groups: docker
        append: yes

    - name: Install Docker Compose
      remote_user: ubuntu
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        mode: u+x,g+x,o+x

    - name: copy docker-compose file from host to remote
      remote_user: ubuntu
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: run docker-compose up
      remote_user: ubuntu
      shell: docker-compose -f /home/ubuntu/docker-compose.yml up -d
