---
- hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars_files:
    - vars/docker.yml

  tasks:
    - name: Install Docker compose
      script: ./compose_install.sh

    - name: copy docker-compose file from host to remote
      become: true
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: run docker-compose up
      become: true
      shell: docker-compose -f /home/ubuntu/docker-compose.yml up -d
